version: '3.8'

services:
  # Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: breconomy-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=breconomy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache
  redis:
    image: redis:alpine
    container_name: breconomy-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: