version: '3.8'

services:

  breconomy.api:
    build:
      context: .
      dockerfile: BrEconomy.API/Dockerfile
    depends_on:
      - db
      - redis

  # Banco de Dados
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: breconomy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: